# permissions to do edit baremetalhardwares.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: baremetalhardware-editor-role
rules:
- apiGroups:
  - baremetal.com.rmb938
  resources:
  - baremetalhardwares
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - baremetal.com.rmb938
  resources:
  - baremetalhardwares/status
  verbs:
  - get
  - patch
  - update
