# permissions to do viewer baremetaldiscoveries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: baremetaldiscovery-viewer-role
rules:
- apiGroups:
  - baremetal.com.rmb938
  resources:
  - baremetaldiscoveries
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - baremetal.com.rmb938
  resources:
  - baremetaldiscoveries/status
  verbs:
  - get
