# permissions to do viewer baremetalhardwares.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: baremetalhardware-viewer-role
rules:
- apiGroups:
  - baremetal.com.rmb938
  resources:
  - baremetalhardwares
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - baremetal.com.rmb938
  resources:
  - baremetalhardwares/status
  verbs:
  - get
